Added db restore script + fixed issue with production SSL certs

diff --git a/moodle-install b/moodle-install
--- a/moodle-install
+++ b/moodle-install
@@ -77,7 +77,9 @@ MDL_DIR=~/moodle
 MDL_DATA=/var/www/moodle_data
 DB_BACKUP_DIR=/var/backups/postgresql
 DB_BACKUP_SCRIPT=/usr/local/bin/db_backup
+DB_RESTORE_SCRIPT=/usr/local/bin/db_restore
 DB_BACKUP_LOG=/var/log/db_backup.log
+DB_RESTORE_LOG=/var/log/db_restore.log
 HR=--------------------------------------------------------------------------------
 
 # Parse command-line arguments
@@ -199,8 +201,8 @@ fi
 # Create database
 if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw moodle; then
     echo_pink "$HR\n Creating Postgres database and Moodle data directory...\n$HR"
-    sudo -u postgres psql -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS'"
-    sudo -u postgres psql -U postgres -c "CREATE DATABASE moodle WITH OWNER $DB_USER"
+    sudo -u postgres psql -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
+    sudo -u postgres psql -U postgres -c "CREATE DATABASE moodle WITH OWNER $DB_USER;"
 else
     echo "Moodle database exists. Skipping..."
 fi
@@ -240,6 +242,60 @@ else
     echo "Database backup tasks exists. Skipping..."
 fi
 
+# Restore db from latest backup
+sudo touch $DB_RESTORE_LOG && sudo chown postgres:postgres $DB_RESTORE_LOG && sudo chmod 640 $DB_BACKUP_LOG
+echo "Creating script at $DB_RESTORE_SCRIPT:"
+sudo tee "$DB_RESTORE_SCRIPT" << EOF
+#!/bin/bash
+set -o pipefail # ensure errors propagate through tee commands
+
+# Find latest backup file
+echo "Locating latest database backup..." | tee -a $DB_RESTORE_LOG
+LATEST_BACKUP="$DB_BACKUP_DIR/\$(sudo -u postgres ls -t $DB_BACKUP_DIR 2>/dev/null | head -n 1)"
+if [ -z \$LATEST_BACKUP]; then
+    echo "Error: No backup files found in $DB_BACKUP_DIR. Aborting..." | tee -a $DB_RESTORE_LOG
+    exit 1
+fi
+echo "Located database backup at: \$LATEST_BACKUP"
+
+# Terminate active db connections
+echo "Terminating active database connections..." | tee -a $DB_RESTORE_LOG
+if ! sudo -u postgres psql postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'moodle';" 2>&1 | tee -a $DB_RESTORE_LOG; then
+    echo "Error: Failed to terminate active connections. Aborting..." | tee -a $DB_RESTORE_LOG
+    exit 1
+fi
+echo "Active connections terminated." | tee -a $DB_RESTORE_LOG
+
+# Drop existing database
+echo "Dropping the existing database..." | tee -a $DB_RESTORE_LOG
+if ! sudo -u postgres psql postgres -c "DROP DATABASE moodle;" 2>&1 | tee -a $DB_RESTORE_LOG; then
+    echo "Error: Failed to drop existing database. Aborting..." | tee -a $DB_RESTORE_LOG
+    exit 1
+fi
+echo "Moodle database dropped successfully." | tee -a $DB_RESTORE_LOG
+
+# Create new empty database
+echo "Creating a new empty database..." | tee -a $DB_RESTORE_LOG
+if ! sudo -u postgres psql postgres -c "CREATE DATABASE moodle WITH OWNER \"$DB_USER\";" 2>&1 | tee -a "$DB_RESTORE_LOG"; then
+    echo "Error: Failed to create moodle database. Aborting..." | tee -a $DB_RESTORE_LOG
+    exit 1
+fi
+echo "Empty database created successfully." | tee -a $DB_RESTORE_LOG
+
+# Restore backup
+echo "Restoring database from backup..." | tee -a $DB_RESTORE_LOG
+if ! sudo -u postgres pg_restore -v -U postgres -d moodle "\$LATEST_BACKUP" 2>&1 | tee -a $DB_RESTORE_LOG; then
+    echo "Error: Failed to restore database from backup. Aborting..." | tee -a $DB_RESTORE_LOG
+    exit 1
+fi
+echo "Database restored successfully." | tee -a $DB_RESTORE_LOG
+
+# Run analyze command for postgresql optimizer
+echo "Running analyzer..." | tee -a $DB_RESTORE_LOG
+sudo -u postgres psql -U postgres -d "moodle" -c "ANALYZE;" 2>&1 | tee -a $DB_RESTORE_LOG
+EOF
+sudo chmod +x $DB_RESTORE_SCRIPT
+
 # Create moodledata directory
 if [ ! -d "$MDL_DATA" ]; then
     sudo mkdir $MDL_DATA && sudo chown -R www-data:www-data $MDL_DATA && sudo chmod 0755 $MDL_DATA
@@ -252,7 +308,7 @@ if [ ! -f $MDL_DIR/config.php ]; then
     echo_pink "$HR\n Running Moodle installer...\n$HR"
     sudo chown -R www-data:www-data $MDL_DIR
     sudo -u www-data php -d max_input_vars=5000 $MDL_DIR/admin/cli/install.php --agree-license --lang=en --wwwroot="https://$WEB_ROOT" --dataroot=$MDL_DATA --dbtype=pgsql --dbuser="$DB_USER" --dbpass="$DB_PASS" --dbport=5432 --fullname="$SITE_NAME" --shortname="$SHORT_NAME" --adminuser="$ADMIN_USER" --adminpass="$ADMIN_PASS" --non-interactive
-    sudo chown -R root:www-data $MDL_DIR && sudo chmod -R 0755 $MDL_DIR $MDL_DATA
+    sudo chown -R root:www-data $MDL_DIR && sudo chmod -R 775 $MDL_DIR $MDL_DATA
 else
     echo "Moodle configuration file exists. Skipping..."
 fi
@@ -352,6 +408,7 @@ case "$IS_PROD" in
         echo_pink "$HR\nCreating production SSL certificate\n$HR"
         sudo apt install certbot python3-certbot-apache
         sudo certbot --apache
+        sed -i "\#Redirect permanent / https://$WEB_ROOT#d" "/etc/apache2/sites-available/moodle-le-ssl.conf"
     ;;
     [Nn] )
         echo_pink "$HR\nCreating local development SSL certificate\n$HR"
